// No simulated product screens, offices or people are presented as real assets.
import { business } from "./business";

export const assets = [
  ...business.flatMap((area) =>
    (["card", "detail"] as const).map((placement) => ({
      id: `${area.id}-${placement}-v1`,
      path: placement === "card" ? area.visual : area.detailVisual,
      kind: "generated" as const,
      source: "Built-in image_gen; see docs/business-thumbnails-v1.json",
      role: `symbolic business illustration (${placement})`,
      altKey: `business.areas.${area.id}.${placement === "card" ? "visualAlt" : "detailVisualAlt"}`,
      permission: "Created for this site at the Owner's request",
      status: "created-for-review" as const,
    })),
  ),
  {
    id: "afterglow",
    path: "/images/afterglow.webp",
    kind: "generated",
    source: "Original supplied handoff",
    role: "abstract brand visual",
    altKey: "assets.afterglowAlt",
    permission: "Previously supplied for this site; see original handoff",
    status: "existing",
  },
  {
    id: "daylight",
    path: "/images/daylight.webp",
    kind: "generated",
    source: "Original supplied handoff",
    role: "abstract brand visual",
    altKey: "assets.daylightAlt",
    permission: "Previously supplied for this site; see original handoff",
    status: "existing",
  },
  {
    id: "business-concept",
    path: null,
    kind: "html-concept",
    source: "This implementation",
    role: "candidate audience and service explanation",
    altKey: "diagram.title and diagram.caption (HTML text)",
    permission: "Created for this site",
    status: "review",
  },
  {
    id: "discovery-screen",
    path: null,
    kind: "development-screen",
    source: null,
    role: "actual service overview",
    permission: null,
    alt: { ja: null, en: null },
    status: "awaiting-approved-material",
  },
  {
    id: "interaction-screen",
    path: null,
    kind: "development-screen",
    source: null,
    role: "actual service interaction",
    permission: null,
    alt: { ja: null, en: null },
    status: "awaiting-approved-material",
  },
  {
    id: "company-photo",
    path: null,
    kind: "photograph",
    source: null,
    role: "actual company or representative",
    permission: null,
    alt: { ja: null, en: null },
    status: "awaiting-approved-material",
  },
  {
    id: "service-video",
    path: null,
    kind: "video",
    source: null,
    role: "optional service explanation",
    permission: null,
    alt: { ja: null, en: null },
    status: "awaiting-approved-material",
  },
] as const;
